//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PendulumInterfaces
{
    [Serializable]
    public class SetpointStateMsg : Message
    {
        public const string k_RosMessageName = "pendulum_interfaces/SetpointState";
        public override string RosMessageName => k_RosMessageName;

        // 목표 펜듈럼 각도
        public double target_angle;
        // 현재 측정된 펜듈럼 각도
        public double current_angle;

        public SetpointStateMsg()
        {
            this.target_angle = 0.0;
            this.current_angle = 0.0;
        }

        public SetpointStateMsg(double target_angle, double current_angle)
        {
            this.target_angle = target_angle;
            this.current_angle = current_angle;
        }

        public static SetpointStateMsg Deserialize(MessageDeserializer deserializer) => new SetpointStateMsg(deserializer);

        private SetpointStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.target_angle);
            deserializer.Read(out this.current_angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_angle);
            serializer.Write(this.current_angle);
        }

        public override string ToString()
        {
            return "SetpointStateMsg: " +
            "\ntarget_angle: " + target_angle.ToString() +
            "\ncurrent_angle: " + current_angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
