//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZeroInterfaces
{
    [Serializable]
    public class CmdVelMsg : Message
    {
        public const string k_RosMessageName = "zero_interfaces/CmdVel";
        public override string RosMessageName => k_RosMessageName;

        public float fl_vel;
        public float bl_vel;
        public float fr_vel;
        public float br_vel;
        public float fl_ang;
        public float bl_ang;
        public float fr_ang;
        public float br_ang;

        public CmdVelMsg()
        {
            this.fl_vel = 0.0f;
            this.bl_vel = 0.0f;
            this.fr_vel = 0.0f;
            this.br_vel = 0.0f;
            this.fl_ang = 0.0f;
            this.bl_ang = 0.0f;
            this.fr_ang = 0.0f;
            this.br_ang = 0.0f;
        }

        public CmdVelMsg(float fl_vel, float bl_vel, float fr_vel, float br_vel, float fl_ang, float bl_ang, float fr_ang, float br_ang)
        {
            this.fl_vel = fl_vel;
            this.bl_vel = bl_vel;
            this.fr_vel = fr_vel;
            this.br_vel = br_vel;
            this.fl_ang = fl_ang;
            this.bl_ang = bl_ang;
            this.fr_ang = fr_ang;
            this.br_ang = br_ang;
        }

        public static CmdVelMsg Deserialize(MessageDeserializer deserializer) => new CmdVelMsg(deserializer);

        private CmdVelMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.fl_vel);
            deserializer.Read(out this.bl_vel);
            deserializer.Read(out this.fr_vel);
            deserializer.Read(out this.br_vel);
            deserializer.Read(out this.fl_ang);
            deserializer.Read(out this.bl_ang);
            deserializer.Read(out this.fr_ang);
            deserializer.Read(out this.br_ang);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.fl_vel);
            serializer.Write(this.bl_vel);
            serializer.Write(this.fr_vel);
            serializer.Write(this.br_vel);
            serializer.Write(this.fl_ang);
            serializer.Write(this.bl_ang);
            serializer.Write(this.fr_ang);
            serializer.Write(this.br_ang);
        }

        public override string ToString()
        {
            return "CmdVelMsg: " +
            "\nfl_vel: " + fl_vel.ToString() +
            "\nbl_vel: " + bl_vel.ToString() +
            "\nfr_vel: " + fr_vel.ToString() +
            "\nbr_vel: " + br_vel.ToString() +
            "\nfl_ang: " + fl_ang.ToString() +
            "\nbl_ang: " + bl_ang.ToString() +
            "\nfr_ang: " + fr_ang.ToString() +
            "\nbr_ang: " + br_ang.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
