//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZeroInterfaces
{
    [Serializable]
    public class ControlInputMsg : Message
    {
        public const string k_RosMessageName = "zero_interfaces/ControlInput";
        public override string RosMessageName => k_RosMessageName;

        public float v;
        public float w;

        public ControlInputMsg()
        {
            this.v = 0.0f;
            this.w = 0.0f;
        }

        public ControlInputMsg(float v, float w)
        {
            this.v = v;
            this.w = w;
        }

        public static ControlInputMsg Deserialize(MessageDeserializer deserializer) => new ControlInputMsg(deserializer);

        private ControlInputMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.v);
            deserializer.Read(out this.w);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.v);
            serializer.Write(this.w);
        }

        public override string ToString()
        {
            return "ControlInputMsg: " +
            "\nv: " + v.ToString() +
            "\nw: " + w.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
