//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZenithInterfaces
{
    [Serializable]
    public class LaunchResultMsg : Message
    {
        public const string k_RosMessageName = "zenith_interfaces/LaunchResult";
        public override string RosMessageName => k_RosMessageName;

        //  런치 실행의 최종 결과
        public bool success;
        public string message;

        public LaunchResultMsg()
        {
            this.success = false;
            this.message = "";
        }

        public LaunchResultMsg(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }

        public static LaunchResultMsg Deserialize(MessageDeserializer deserializer) => new LaunchResultMsg(deserializer);

        private LaunchResultMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "LaunchResultMsg: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
