//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZenithInterfaces
{
    [Serializable]
    public class CommandResponse : Message
    {
        public const string k_RosMessageName = "zenith_interfaces/Command";
        public override string RosMessageName => k_RosMessageName;

        //  응답: 성공 여부와 메시지
        public bool success;
        public string message;

        public CommandResponse()
        {
            this.success = false;
            this.message = "";
        }

        public CommandResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }

        public static CommandResponse Deserialize(MessageDeserializer deserializer) => new CommandResponse(deserializer);

        private CommandResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "CommandResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
