//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZenithInterfaces
{
    [Serializable]
    public class CommandRequest : Message
    {
        public const string k_RosMessageName = "zenith_interfaces/Command";
        public override string RosMessageName => k_RosMessageName;

        //  요청: 문자열 명령
        public string command;

        public CommandRequest()
        {
            this.command = "";
        }

        public CommandRequest(string command)
        {
            this.command = command;
        }

        public static CommandRequest Deserialize(MessageDeserializer deserializer) => new CommandRequest(deserializer);

        private CommandRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
        }

        public override string ToString()
        {
            return "CommandRequest: " +
            "\ncommand: " + command.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
