//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZenithInterfaces
{
    [Serializable]
    public class EmergencyRequest : Message
    {
        public const string k_RosMessageName = "zenith_interfaces/Emergency";
        public override string RosMessageName => k_RosMessageName;

        //  요청은 비어 있음

        public EmergencyRequest()
        {
        }
        public static EmergencyRequest Deserialize(MessageDeserializer deserializer) => new EmergencyRequest(deserializer);

        private EmergencyRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "EmergencyRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
