//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZenithInterfaces
{
    [Serializable]
    public class EmergencyResponse : Message
    {
        public const string k_RosMessageName = "zenith_interfaces/Emergency";
        public override string RosMessageName => k_RosMessageName;

        //  응답으로 성공 여부를 전달
        public bool success;

        public EmergencyResponse()
        {
            this.success = false;
        }

        public EmergencyResponse(bool success)
        {
            this.success = success;
        }

        public static EmergencyResponse Deserialize(MessageDeserializer deserializer) => new EmergencyResponse(deserializer);

        private EmergencyResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "EmergencyResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
