//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZenithInterfaces
{
    [Serializable]
    public class GetTopicListRequest : Message
    {
        public const string k_RosMessageName = "zenith_interfaces/GetTopicList";
        public override string RosMessageName => k_RosMessageName;

        //  요청은 비어있음

        public GetTopicListRequest()
        {
        }
        public static GetTopicListRequest Deserialize(MessageDeserializer deserializer) => new GetTopicListRequest(deserializer);

        private GetTopicListRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetTopicListRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
