//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZenithInterfaces
{
    [Serializable]
    public class GetTopicListResponse : Message
    {
        public const string k_RosMessageName = "zenith_interfaces/GetTopicList";
        public override string RosMessageName => k_RosMessageName;

        //  응답: 토픽 이름 목록과 타입 목록
        public string[] topic_names;
        public string[] topic_types;

        public GetTopicListResponse()
        {
            this.topic_names = new string[0];
            this.topic_types = new string[0];
        }

        public GetTopicListResponse(string[] topic_names, string[] topic_types)
        {
            this.topic_names = topic_names;
            this.topic_types = topic_types;
        }

        public static GetTopicListResponse Deserialize(MessageDeserializer deserializer) => new GetTopicListResponse(deserializer);

        private GetTopicListResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.topic_names, deserializer.ReadLength());
            deserializer.Read(out this.topic_types, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.topic_names);
            serializer.Write(this.topic_names);
            serializer.WriteLength(this.topic_types);
            serializer.Write(this.topic_types);
        }

        public override string ToString()
        {
            return "GetTopicListResponse: " +
            "\ntopic_names: " + System.String.Join(", ", topic_names.ToList()) +
            "\ntopic_types: " + System.String.Join(", ", topic_types.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
