//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZenithInterfaces
{
    [Serializable]
    public class StartLaunchRequest : Message
    {
        public const string k_RosMessageName = "zenith_interfaces/StartLaunch";
        public override string RosMessageName => k_RosMessageName;

        //  요청: 실행할 런치 파일 정보
        public string package_name;
        public string launch_file_name;

        public StartLaunchRequest()
        {
            this.package_name = "";
            this.launch_file_name = "";
        }

        public StartLaunchRequest(string package_name, string launch_file_name)
        {
            this.package_name = package_name;
            this.launch_file_name = launch_file_name;
        }

        public static StartLaunchRequest Deserialize(MessageDeserializer deserializer) => new StartLaunchRequest(deserializer);

        private StartLaunchRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.package_name);
            deserializer.Read(out this.launch_file_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.package_name);
            serializer.Write(this.launch_file_name);
        }

        public override string ToString()
        {
            return "StartLaunchRequest: " +
            "\npackage_name: " + package_name.ToString() +
            "\nlaunch_file_name: " + launch_file_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
