//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZenithInterfaces
{
    [Serializable]
    public class StartLaunchResponse : Message
    {
        public const string k_RosMessageName = "zenith_interfaces/StartLaunch";
        public override string RosMessageName => k_RosMessageName;

        //  응답: 요청이 잘 접수되었는지 여부
        public bool success;
        public string message;

        public StartLaunchResponse()
        {
            this.success = false;
            this.message = "";
        }

        public StartLaunchResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }

        public static StartLaunchResponse Deserialize(MessageDeserializer deserializer) => new StartLaunchResponse(deserializer);

        private StartLaunchResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "StartLaunchResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
