//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZenithInterfaces
{
    [Serializable]
    public class TriggerResponse : Message
    {
        public const string k_RosMessageName = "zenith_interfaces/Trigger";
        public override string RosMessageName => k_RosMessageName;

        //  응답: 성공 여부
        public bool success;

        public TriggerResponse()
        {
            this.success = false;
        }

        public TriggerResponse(bool success)
        {
            this.success = success;
        }

        public static TriggerResponse Deserialize(MessageDeserializer deserializer) => new TriggerResponse(deserializer);

        private TriggerResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "TriggerResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
